// Generated by gencpp from file dji_sdk/MFIOConfig.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_MFIOCONFIG_H
#define DJI_SDK_MESSAGE_MFIOCONFIG_H

#include <ros/service_traits.h>


#include <dji_sdk/MFIOConfigRequest.h>
#include <dji_sdk/MFIOConfigResponse.h>


namespace dji_sdk
{

struct MFIOConfig
{

typedef MFIOConfigRequest Request;
typedef MFIOConfigResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MFIOConfig
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::MFIOConfig > {
  static const char* value()
  {
    return "ad06bda475c7f13453680ee626114de0";
  }

  static const char* value(const ::dji_sdk::MFIOConfig&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::MFIOConfig > {
  static const char* value()
  {
    return "dji_sdk/MFIOConfig";
  }

  static const char* value(const ::dji_sdk::MFIOConfig&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::MFIOConfigRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::MFIOConfig > 
template<>
struct MD5Sum< ::dji_sdk::MFIOConfigRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::MFIOConfig >::value();
  }
  static const char* value(const ::dji_sdk::MFIOConfigRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::MFIOConfigRequest> should match 
// service_traits::DataType< ::dji_sdk::MFIOConfig > 
template<>
struct DataType< ::dji_sdk::MFIOConfigRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::MFIOConfig >::value();
  }
  static const char* value(const ::dji_sdk::MFIOConfigRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::MFIOConfigResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::MFIOConfig > 
template<>
struct MD5Sum< ::dji_sdk::MFIOConfigResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::MFIOConfig >::value();
  }
  static const char* value(const ::dji_sdk::MFIOConfigResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::MFIOConfigResponse> should match 
// service_traits::DataType< ::dji_sdk::MFIOConfig > 
template<>
struct DataType< ::dji_sdk::MFIOConfigResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::MFIOConfig >::value();
  }
  static const char* value(const ::dji_sdk::MFIOConfigResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_MFIOCONFIG_H
