// Generated by gencpp from file dji_sdk/MissionHpAction.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_MISSIONHPACTION_H
#define DJI_SDK_MESSAGE_MISSIONHPACTION_H

#include <ros/service_traits.h>


#include <dji_sdk/MissionHpActionRequest.h>
#include <dji_sdk/MissionHpActionResponse.h>


namespace dji_sdk
{

struct MissionHpAction
{

typedef MissionHpActionRequest Request;
typedef MissionHpActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionHpAction
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::MissionHpAction > {
  static const char* value()
  {
    return "067ec5f79e77e0b4c0121e09e733b483";
  }

  static const char* value(const ::dji_sdk::MissionHpAction&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::MissionHpAction > {
  static const char* value()
  {
    return "dji_sdk/MissionHpAction";
  }

  static const char* value(const ::dji_sdk::MissionHpAction&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::MissionHpActionRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::MissionHpAction > 
template<>
struct MD5Sum< ::dji_sdk::MissionHpActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::MissionHpAction >::value();
  }
  static const char* value(const ::dji_sdk::MissionHpActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::MissionHpActionRequest> should match 
// service_traits::DataType< ::dji_sdk::MissionHpAction > 
template<>
struct DataType< ::dji_sdk::MissionHpActionRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::MissionHpAction >::value();
  }
  static const char* value(const ::dji_sdk::MissionHpActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::MissionHpActionResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::MissionHpAction > 
template<>
struct MD5Sum< ::dji_sdk::MissionHpActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::MissionHpAction >::value();
  }
  static const char* value(const ::dji_sdk::MissionHpActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::MissionHpActionResponse> should match 
// service_traits::DataType< ::dji_sdk::MissionHpAction > 
template<>
struct DataType< ::dji_sdk::MissionHpActionResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::MissionHpAction >::value();
  }
  static const char* value(const ::dji_sdk::MissionHpActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_MISSIONHPACTION_H
