// Generated by gencpp from file dji_sdk/MissionWpGetInfo.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_MISSIONWPGETINFO_H
#define DJI_SDK_MESSAGE_MISSIONWPGETINFO_H

#include <ros/service_traits.h>


#include <dji_sdk/MissionWpGetInfoRequest.h>
#include <dji_sdk/MissionWpGetInfoResponse.h>


namespace dji_sdk
{

struct MissionWpGetInfo
{

typedef MissionWpGetInfoRequest Request;
typedef MissionWpGetInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionWpGetInfo
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::MissionWpGetInfo > {
  static const char* value()
  {
    return "412556517acb90aa4c3e713fbb867865";
  }

  static const char* value(const ::dji_sdk::MissionWpGetInfo&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::MissionWpGetInfo > {
  static const char* value()
  {
    return "dji_sdk/MissionWpGetInfo";
  }

  static const char* value(const ::dji_sdk::MissionWpGetInfo&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::MissionWpGetInfoRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::MissionWpGetInfo > 
template<>
struct MD5Sum< ::dji_sdk::MissionWpGetInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::MissionWpGetInfo >::value();
  }
  static const char* value(const ::dji_sdk::MissionWpGetInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::MissionWpGetInfoRequest> should match 
// service_traits::DataType< ::dji_sdk::MissionWpGetInfo > 
template<>
struct DataType< ::dji_sdk::MissionWpGetInfoRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::MissionWpGetInfo >::value();
  }
  static const char* value(const ::dji_sdk::MissionWpGetInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::MissionWpGetInfoResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::MissionWpGetInfo > 
template<>
struct MD5Sum< ::dji_sdk::MissionWpGetInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::MissionWpGetInfo >::value();
  }
  static const char* value(const ::dji_sdk::MissionWpGetInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::MissionWpGetInfoResponse> should match 
// service_traits::DataType< ::dji_sdk::MissionWpGetInfo > 
template<>
struct DataType< ::dji_sdk::MissionWpGetInfoResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::MissionWpGetInfo >::value();
  }
  static const char* value(const ::dji_sdk::MissionWpGetInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_MISSIONWPGETINFO_H
