// Generated by gencpp from file dji_sdk/MissionHpUpdateYawRate.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_MISSIONHPUPDATEYAWRATE_H
#define DJI_SDK_MESSAGE_MISSIONHPUPDATEYAWRATE_H

#include <ros/service_traits.h>


#include <dji_sdk/MissionHpUpdateYawRateRequest.h>
#include <dji_sdk/MissionHpUpdateYawRateResponse.h>


namespace dji_sdk
{

struct MissionHpUpdateYawRate
{

typedef MissionHpUpdateYawRateRequest Request;
typedef MissionHpUpdateYawRateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionHpUpdateYawRate
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::MissionHpUpdateYawRate > {
  static const char* value()
  {
    return "e4b46552667899a74d58ef421a1fe415";
  }

  static const char* value(const ::dji_sdk::MissionHpUpdateYawRate&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::MissionHpUpdateYawRate > {
  static const char* value()
  {
    return "dji_sdk/MissionHpUpdateYawRate";
  }

  static const char* value(const ::dji_sdk::MissionHpUpdateYawRate&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::MissionHpUpdateYawRateRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::MissionHpUpdateYawRate > 
template<>
struct MD5Sum< ::dji_sdk::MissionHpUpdateYawRateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::MissionHpUpdateYawRate >::value();
  }
  static const char* value(const ::dji_sdk::MissionHpUpdateYawRateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::MissionHpUpdateYawRateRequest> should match 
// service_traits::DataType< ::dji_sdk::MissionHpUpdateYawRate > 
template<>
struct DataType< ::dji_sdk::MissionHpUpdateYawRateRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::MissionHpUpdateYawRate >::value();
  }
  static const char* value(const ::dji_sdk::MissionHpUpdateYawRateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::MissionHpUpdateYawRateResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::MissionHpUpdateYawRate > 
template<>
struct MD5Sum< ::dji_sdk::MissionHpUpdateYawRateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::MissionHpUpdateYawRate >::value();
  }
  static const char* value(const ::dji_sdk::MissionHpUpdateYawRateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::MissionHpUpdateYawRateResponse> should match 
// service_traits::DataType< ::dji_sdk::MissionHpUpdateYawRate > 
template<>
struct DataType< ::dji_sdk::MissionHpUpdateYawRateResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::MissionHpUpdateYawRate >::value();
  }
  static const char* value(const ::dji_sdk::MissionHpUpdateYawRateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_MISSIONHPUPDATEYAWRATE_H
