// Generated by gencpp from file dji_sdk/MissionHpUpdateRadius.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_MISSIONHPUPDATERADIUS_H
#define DJI_SDK_MESSAGE_MISSIONHPUPDATERADIUS_H

#include <ros/service_traits.h>


#include <dji_sdk/MissionHpUpdateRadiusRequest.h>
#include <dji_sdk/MissionHpUpdateRadiusResponse.h>


namespace dji_sdk
{

struct MissionHpUpdateRadius
{

typedef MissionHpUpdateRadiusRequest Request;
typedef MissionHpUpdateRadiusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionHpUpdateRadius
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::MissionHpUpdateRadius > {
  static const char* value()
  {
    return "a73ee6c10e003f74ced091fcaa0531af";
  }

  static const char* value(const ::dji_sdk::MissionHpUpdateRadius&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::MissionHpUpdateRadius > {
  static const char* value()
  {
    return "dji_sdk/MissionHpUpdateRadius";
  }

  static const char* value(const ::dji_sdk::MissionHpUpdateRadius&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::MissionHpUpdateRadiusRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::MissionHpUpdateRadius > 
template<>
struct MD5Sum< ::dji_sdk::MissionHpUpdateRadiusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::MissionHpUpdateRadius >::value();
  }
  static const char* value(const ::dji_sdk::MissionHpUpdateRadiusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::MissionHpUpdateRadiusRequest> should match 
// service_traits::DataType< ::dji_sdk::MissionHpUpdateRadius > 
template<>
struct DataType< ::dji_sdk::MissionHpUpdateRadiusRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::MissionHpUpdateRadius >::value();
  }
  static const char* value(const ::dji_sdk::MissionHpUpdateRadiusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::MissionHpUpdateRadiusResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::MissionHpUpdateRadius > 
template<>
struct MD5Sum< ::dji_sdk::MissionHpUpdateRadiusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::MissionHpUpdateRadius >::value();
  }
  static const char* value(const ::dji_sdk::MissionHpUpdateRadiusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::MissionHpUpdateRadiusResponse> should match 
// service_traits::DataType< ::dji_sdk::MissionHpUpdateRadius > 
template<>
struct DataType< ::dji_sdk::MissionHpUpdateRadiusResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::MissionHpUpdateRadius >::value();
  }
  static const char* value(const ::dji_sdk::MissionHpUpdateRadiusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_MISSIONHPUPDATERADIUS_H
