// Generated by gencpp from file dji_sdk/MissionWpAction.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_MISSIONWPACTION_H
#define DJI_SDK_MESSAGE_MISSIONWPACTION_H

#include <ros/service_traits.h>


#include <dji_sdk/MissionWpActionRequest.h>
#include <dji_sdk/MissionWpActionResponse.h>


namespace dji_sdk
{

struct MissionWpAction
{

typedef MissionWpActionRequest Request;
typedef MissionWpActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionWpAction
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::MissionWpAction > {
  static const char* value()
  {
    return "067ec5f79e77e0b4c0121e09e733b483";
  }

  static const char* value(const ::dji_sdk::MissionWpAction&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::MissionWpAction > {
  static const char* value()
  {
    return "dji_sdk/MissionWpAction";
  }

  static const char* value(const ::dji_sdk::MissionWpAction&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::MissionWpActionRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::MissionWpAction > 
template<>
struct MD5Sum< ::dji_sdk::MissionWpActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::MissionWpAction >::value();
  }
  static const char* value(const ::dji_sdk::MissionWpActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::MissionWpActionRequest> should match 
// service_traits::DataType< ::dji_sdk::MissionWpAction > 
template<>
struct DataType< ::dji_sdk::MissionWpActionRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::MissionWpAction >::value();
  }
  static const char* value(const ::dji_sdk::MissionWpActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::MissionWpActionResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::MissionWpAction > 
template<>
struct MD5Sum< ::dji_sdk::MissionWpActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::MissionWpAction >::value();
  }
  static const char* value(const ::dji_sdk::MissionWpActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::MissionWpActionResponse> should match 
// service_traits::DataType< ::dji_sdk::MissionWpAction > 
template<>
struct DataType< ::dji_sdk::MissionWpActionResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::MissionWpAction >::value();
  }
  static const char* value(const ::dji_sdk::MissionWpActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_MISSIONWPACTION_H
