// Generated by gencpp from file dji_sdk/MissionStatus.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_MISSIONSTATUS_H
#define DJI_SDK_MESSAGE_MISSIONSTATUS_H

#include <ros/service_traits.h>


#include <dji_sdk/MissionStatusRequest.h>
#include <dji_sdk/MissionStatusResponse.h>


namespace dji_sdk
{

struct MissionStatus
{

typedef MissionStatusRequest Request;
typedef MissionStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionStatus
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::MissionStatus > {
  static const char* value()
  {
    return "76ed0b909c77c6ce98df135419939be9";
  }

  static const char* value(const ::dji_sdk::MissionStatus&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::MissionStatus > {
  static const char* value()
  {
    return "dji_sdk/MissionStatus";
  }

  static const char* value(const ::dji_sdk::MissionStatus&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::MissionStatusRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::MissionStatus > 
template<>
struct MD5Sum< ::dji_sdk::MissionStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::MissionStatus >::value();
  }
  static const char* value(const ::dji_sdk::MissionStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::MissionStatusRequest> should match 
// service_traits::DataType< ::dji_sdk::MissionStatus > 
template<>
struct DataType< ::dji_sdk::MissionStatusRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::MissionStatus >::value();
  }
  static const char* value(const ::dji_sdk::MissionStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::MissionStatusResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::MissionStatus > 
template<>
struct MD5Sum< ::dji_sdk::MissionStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::MissionStatus >::value();
  }
  static const char* value(const ::dji_sdk::MissionStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::MissionStatusResponse> should match 
// service_traits::DataType< ::dji_sdk::MissionStatus > 
template<>
struct DataType< ::dji_sdk::MissionStatusResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::MissionStatus >::value();
  }
  static const char* value(const ::dji_sdk::MissionStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_MISSIONSTATUS_H
