// Generated by gencpp from file dji_sdk/QueryDroneVersion.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_QUERYDRONEVERSION_H
#define DJI_SDK_MESSAGE_QUERYDRONEVERSION_H

#include <ros/service_traits.h>


#include <dji_sdk/QueryDroneVersionRequest.h>
#include <dji_sdk/QueryDroneVersionResponse.h>


namespace dji_sdk
{

struct QueryDroneVersion
{

typedef QueryDroneVersionRequest Request;
typedef QueryDroneVersionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QueryDroneVersion
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::QueryDroneVersion > {
  static const char* value()
  {
    return "89b6e8d274e31334cc3a372757607be2";
  }

  static const char* value(const ::dji_sdk::QueryDroneVersion&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::QueryDroneVersion > {
  static const char* value()
  {
    return "dji_sdk/QueryDroneVersion";
  }

  static const char* value(const ::dji_sdk::QueryDroneVersion&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::QueryDroneVersionRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::QueryDroneVersion > 
template<>
struct MD5Sum< ::dji_sdk::QueryDroneVersionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::QueryDroneVersion >::value();
  }
  static const char* value(const ::dji_sdk::QueryDroneVersionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::QueryDroneVersionRequest> should match 
// service_traits::DataType< ::dji_sdk::QueryDroneVersion > 
template<>
struct DataType< ::dji_sdk::QueryDroneVersionRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::QueryDroneVersion >::value();
  }
  static const char* value(const ::dji_sdk::QueryDroneVersionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::QueryDroneVersionResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::QueryDroneVersion > 
template<>
struct MD5Sum< ::dji_sdk::QueryDroneVersionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::QueryDroneVersion >::value();
  }
  static const char* value(const ::dji_sdk::QueryDroneVersionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::QueryDroneVersionResponse> should match 
// service_traits::DataType< ::dji_sdk::QueryDroneVersion > 
template<>
struct DataType< ::dji_sdk::QueryDroneVersionResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::QueryDroneVersion >::value();
  }
  static const char* value(const ::dji_sdk::QueryDroneVersionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_QUERYDRONEVERSION_H
