// Generated by gencpp from file dji_sdk/SendPayloadData.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_SENDPAYLOADDATA_H
#define DJI_SDK_MESSAGE_SENDPAYLOADDATA_H

#include <ros/service_traits.h>


#include <dji_sdk/SendPayloadDataRequest.h>
#include <dji_sdk/SendPayloadDataResponse.h>


namespace dji_sdk
{

struct SendPayloadData
{

typedef SendPayloadDataRequest Request;
typedef SendPayloadDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendPayloadData
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::SendPayloadData > {
  static const char* value()
  {
    return "1c25dff3462ed6a8f6df1c148c7b6a1e";
  }

  static const char* value(const ::dji_sdk::SendPayloadData&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::SendPayloadData > {
  static const char* value()
  {
    return "dji_sdk/SendPayloadData";
  }

  static const char* value(const ::dji_sdk::SendPayloadData&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::SendPayloadDataRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::SendPayloadData > 
template<>
struct MD5Sum< ::dji_sdk::SendPayloadDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::SendPayloadData >::value();
  }
  static const char* value(const ::dji_sdk::SendPayloadDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::SendPayloadDataRequest> should match 
// service_traits::DataType< ::dji_sdk::SendPayloadData > 
template<>
struct DataType< ::dji_sdk::SendPayloadDataRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::SendPayloadData >::value();
  }
  static const char* value(const ::dji_sdk::SendPayloadDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::SendPayloadDataResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::SendPayloadData > 
template<>
struct MD5Sum< ::dji_sdk::SendPayloadDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::SendPayloadData >::value();
  }
  static const char* value(const ::dji_sdk::SendPayloadDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::SendPayloadDataResponse> should match 
// service_traits::DataType< ::dji_sdk::SendPayloadData > 
template<>
struct DataType< ::dji_sdk::SendPayloadDataResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::SendPayloadData >::value();
  }
  static const char* value(const ::dji_sdk::SendPayloadDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_SENDPAYLOADDATA_H
