// Generated by gencpp from file dji_sdk/SendMobileData.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_SENDMOBILEDATA_H
#define DJI_SDK_MESSAGE_SENDMOBILEDATA_H

#include <ros/service_traits.h>


#include <dji_sdk/SendMobileDataRequest.h>
#include <dji_sdk/SendMobileDataResponse.h>


namespace dji_sdk
{

struct SendMobileData
{

typedef SendMobileDataRequest Request;
typedef SendMobileDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SendMobileData
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::SendMobileData > {
  static const char* value()
  {
    return "1c25dff3462ed6a8f6df1c148c7b6a1e";
  }

  static const char* value(const ::dji_sdk::SendMobileData&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::SendMobileData > {
  static const char* value()
  {
    return "dji_sdk/SendMobileData";
  }

  static const char* value(const ::dji_sdk::SendMobileData&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::SendMobileDataRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::SendMobileData > 
template<>
struct MD5Sum< ::dji_sdk::SendMobileDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::SendMobileData >::value();
  }
  static const char* value(const ::dji_sdk::SendMobileDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::SendMobileDataRequest> should match 
// service_traits::DataType< ::dji_sdk::SendMobileData > 
template<>
struct DataType< ::dji_sdk::SendMobileDataRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::SendMobileData >::value();
  }
  static const char* value(const ::dji_sdk::SendMobileDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::SendMobileDataResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::SendMobileData > 
template<>
struct MD5Sum< ::dji_sdk::SendMobileDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::SendMobileData >::value();
  }
  static const char* value(const ::dji_sdk::SendMobileDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::SendMobileDataResponse> should match 
// service_traits::DataType< ::dji_sdk::SendMobileData > 
template<>
struct DataType< ::dji_sdk::SendMobileDataResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::SendMobileData >::value();
  }
  static const char* value(const ::dji_sdk::SendMobileDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_SENDMOBILEDATA_H
