// Generated by gencpp from file dji_sdk/SetHardSync.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_SETHARDSYNC_H
#define DJI_SDK_MESSAGE_SETHARDSYNC_H

#include <ros/service_traits.h>


#include <dji_sdk/SetHardSyncRequest.h>
#include <dji_sdk/SetHardSyncResponse.h>


namespace dji_sdk
{

struct SetHardSync
{

typedef SetHardSyncRequest Request;
typedef SetHardSyncResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetHardSync
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::SetHardSync > {
  static const char* value()
  {
    return "11e826f14456b3511264f6a734868e08";
  }

  static const char* value(const ::dji_sdk::SetHardSync&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::SetHardSync > {
  static const char* value()
  {
    return "dji_sdk/SetHardSync";
  }

  static const char* value(const ::dji_sdk::SetHardSync&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::SetHardSyncRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::SetHardSync > 
template<>
struct MD5Sum< ::dji_sdk::SetHardSyncRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::SetHardSync >::value();
  }
  static const char* value(const ::dji_sdk::SetHardSyncRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::SetHardSyncRequest> should match 
// service_traits::DataType< ::dji_sdk::SetHardSync > 
template<>
struct DataType< ::dji_sdk::SetHardSyncRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::SetHardSync >::value();
  }
  static const char* value(const ::dji_sdk::SetHardSyncRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::SetHardSyncResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::SetHardSync > 
template<>
struct MD5Sum< ::dji_sdk::SetHardSyncResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::SetHardSync >::value();
  }
  static const char* value(const ::dji_sdk::SetHardSyncResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::SetHardSyncResponse> should match 
// service_traits::DataType< ::dji_sdk::SetHardSync > 
template<>
struct DataType< ::dji_sdk::SetHardSyncResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::SetHardSync >::value();
  }
  static const char* value(const ::dji_sdk::SetHardSyncResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_SETHARDSYNC_H
