// Generated by gencpp from file dji_sdk/SetLocalPosRef.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_SETLOCALPOSREF_H
#define DJI_SDK_MESSAGE_SETLOCALPOSREF_H

#include <ros/service_traits.h>


#include <dji_sdk/SetLocalPosRefRequest.h>
#include <dji_sdk/SetLocalPosRefResponse.h>


namespace dji_sdk
{

struct SetLocalPosRef
{

typedef SetLocalPosRefRequest Request;
typedef SetLocalPosRefResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLocalPosRef
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::SetLocalPosRef > {
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::dji_sdk::SetLocalPosRef&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::SetLocalPosRef > {
  static const char* value()
  {
    return "dji_sdk/SetLocalPosRef";
  }

  static const char* value(const ::dji_sdk::SetLocalPosRef&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::SetLocalPosRefRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::SetLocalPosRef > 
template<>
struct MD5Sum< ::dji_sdk::SetLocalPosRefRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::SetLocalPosRef >::value();
  }
  static const char* value(const ::dji_sdk::SetLocalPosRefRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::SetLocalPosRefRequest> should match 
// service_traits::DataType< ::dji_sdk::SetLocalPosRef > 
template<>
struct DataType< ::dji_sdk::SetLocalPosRefRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::SetLocalPosRef >::value();
  }
  static const char* value(const ::dji_sdk::SetLocalPosRefRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::SetLocalPosRefResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::SetLocalPosRef > 
template<>
struct MD5Sum< ::dji_sdk::SetLocalPosRefResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::SetLocalPosRef >::value();
  }
  static const char* value(const ::dji_sdk::SetLocalPosRefResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::SetLocalPosRefResponse> should match 
// service_traits::DataType< ::dji_sdk::SetLocalPosRef > 
template<>
struct DataType< ::dji_sdk::SetLocalPosRefResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::SetLocalPosRef >::value();
  }
  static const char* value(const ::dji_sdk::SetLocalPosRefResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_SETLOCALPOSREF_H
