// Generated by gencpp from file dji_sdk/SetupCameraStream.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_SETUPCAMERASTREAM_H
#define DJI_SDK_MESSAGE_SETUPCAMERASTREAM_H

#include <ros/service_traits.h>


#include <dji_sdk/SetupCameraStreamRequest.h>
#include <dji_sdk/SetupCameraStreamResponse.h>


namespace dji_sdk
{

struct SetupCameraStream
{

typedef SetupCameraStreamRequest Request;
typedef SetupCameraStreamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetupCameraStream
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::SetupCameraStream > {
  static const char* value()
  {
    return "e0732f307563f64841a2e5c6880f32d3";
  }

  static const char* value(const ::dji_sdk::SetupCameraStream&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::SetupCameraStream > {
  static const char* value()
  {
    return "dji_sdk/SetupCameraStream";
  }

  static const char* value(const ::dji_sdk::SetupCameraStream&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::SetupCameraStreamRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::SetupCameraStream > 
template<>
struct MD5Sum< ::dji_sdk::SetupCameraStreamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::SetupCameraStream >::value();
  }
  static const char* value(const ::dji_sdk::SetupCameraStreamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::SetupCameraStreamRequest> should match 
// service_traits::DataType< ::dji_sdk::SetupCameraStream > 
template<>
struct DataType< ::dji_sdk::SetupCameraStreamRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::SetupCameraStream >::value();
  }
  static const char* value(const ::dji_sdk::SetupCameraStreamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::SetupCameraStreamResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::SetupCameraStream > 
template<>
struct MD5Sum< ::dji_sdk::SetupCameraStreamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::SetupCameraStream >::value();
  }
  static const char* value(const ::dji_sdk::SetupCameraStreamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::SetupCameraStreamResponse> should match 
// service_traits::DataType< ::dji_sdk::SetupCameraStream > 
template<>
struct DataType< ::dji_sdk::SetupCameraStreamResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::SetupCameraStream >::value();
  }
  static const char* value(const ::dji_sdk::SetupCameraStreamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_SETUPCAMERASTREAM_H
