// Generated by gencpp from file dji_sdk/Stereo240pSubscription.msg
// DO NOT EDIT!


#ifndef DJI_SDK_MESSAGE_STEREO240PSUBSCRIPTION_H
#define DJI_SDK_MESSAGE_STEREO240PSUBSCRIPTION_H

#include <ros/service_traits.h>


#include <dji_sdk/Stereo240pSubscriptionRequest.h>
#include <dji_sdk/Stereo240pSubscriptionResponse.h>


namespace dji_sdk
{

struct Stereo240pSubscription
{

typedef Stereo240pSubscriptionRequest Request;
typedef Stereo240pSubscriptionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Stereo240pSubscription
} // namespace dji_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_sdk::Stereo240pSubscription > {
  static const char* value()
  {
    return "c1205f3b01904555b852bb2bc5881da0";
  }

  static const char* value(const ::dji_sdk::Stereo240pSubscription&) { return value(); }
};

template<>
struct DataType< ::dji_sdk::Stereo240pSubscription > {
  static const char* value()
  {
    return "dji_sdk/Stereo240pSubscription";
  }

  static const char* value(const ::dji_sdk::Stereo240pSubscription&) { return value(); }
};


// service_traits::MD5Sum< ::dji_sdk::Stereo240pSubscriptionRequest> should match 
// service_traits::MD5Sum< ::dji_sdk::Stereo240pSubscription > 
template<>
struct MD5Sum< ::dji_sdk::Stereo240pSubscriptionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::Stereo240pSubscription >::value();
  }
  static const char* value(const ::dji_sdk::Stereo240pSubscriptionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::Stereo240pSubscriptionRequest> should match 
// service_traits::DataType< ::dji_sdk::Stereo240pSubscription > 
template<>
struct DataType< ::dji_sdk::Stereo240pSubscriptionRequest>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::Stereo240pSubscription >::value();
  }
  static const char* value(const ::dji_sdk::Stereo240pSubscriptionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_sdk::Stereo240pSubscriptionResponse> should match 
// service_traits::MD5Sum< ::dji_sdk::Stereo240pSubscription > 
template<>
struct MD5Sum< ::dji_sdk::Stereo240pSubscriptionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_sdk::Stereo240pSubscription >::value();
  }
  static const char* value(const ::dji_sdk::Stereo240pSubscriptionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_sdk::Stereo240pSubscriptionResponse> should match 
// service_traits::DataType< ::dji_sdk::Stereo240pSubscription > 
template<>
struct DataType< ::dji_sdk::Stereo240pSubscriptionResponse>
{
  static const char* value()
  {
    return DataType< ::dji_sdk::Stereo240pSubscription >::value();
  }
  static const char* value(const ::dji_sdk::Stereo240pSubscriptionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_SDK_MESSAGE_STEREO240PSUBSCRIPTION_H
