(cl:defpackage apriltags2_ros-srv
  (:use )
  (:export
   "ANALYZESINGLEIMAGE"
   "<ANALYZESINGLEIMAGE-REQUEST>"
   "ANALYZESINGLEIMAGE-REQUEST"
   "<ANALYZESINGLEIMAGE-RESPONSE>"
   "ANALYZESINGLEIMAGE-RESPONSE"
  ))

